Fail if anything goes wrong.

diff --git a/svn-to-git b/svn-to-git
--- a/svn-to-git
+++ b/svn-to-git
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# Fail on an error
+set -e
+
 absdir() {                                               
   echo "$(cd "$(dirname "$1")" && pwd)/"
 }
